# Generated by Django 5.2.7 on 2025-12-18 18:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('meralcoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('change_type', models.CharField(choices=[('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'change_logs',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DelayFactor',
            fields=[
                ('factor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_name', models.CharField(max_length=100, unique=True)),
                ('factor_category', models.CharField(blank=True, max_length=50, null=True)),
                ('factor_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delay_factors',
                'ordering': ['factor_category', 'factor_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('overdue_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_compliance',
                'ordering': ['project', 'doc_type'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('rule_description', models.TextField(blank=True, null=True)),
                ('trigger_condition', models.CharField(max_length=255)),
                ('delay_threshold_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'escalation_rules',
                'ordering': ['rule_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('inspection_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_name', models.CharField(max_length=100, unique=True)),
                ('inspection_description', models.TextField(blank=True, null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inspection_types',
                'ordering': ['inspection_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Unpaid', max_length=50)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDelay',
            fields=[
                ('delay_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delay_days', models.IntegerField()),
                ('delay_start_date', models.DateField()),
                ('delay_end_date', models.DateField(blank=True, null=True)),
                ('responsible_party', models.CharField(blank=True, choices=[('Vendor', 'Vendor'), ('Internal', 'Internal'), ('External', 'External')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_delays',
                'ordering': ['-delay_start_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=255)),
                ('milestone_description', models.TextField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('milestone_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_milestones',
                'ordering': ['milestone_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('status_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('status_order', models.IntegerField(blank=True, null=True)),
                ('status_color', models.CharField(blank=True, max_length=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project Statuses',
                'db_table': 'project_status',
                'ordering': ['status_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_team',
                'ordering': ['project', '-is_active'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Blocked', 'Blocked')], default='Pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_current_stage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_workflow',
                'ordering': ['project', 'stage__stage_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QIDailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('target_audits', models.IntegerField()),
                ('actual_audits', models.IntegerField(default=0)),
                ('target_met', models.BooleanField(default=False)),
                ('reason_not_met', models.TextField(blank=True, null=True)),
                ('reason_category', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qi_daily_targets',
                'ordering': ['-target_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QIInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('inspection_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Conditional', 'Conditional')], max_length=50, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('photos_uploaded', models.BooleanField(default=False)),
                ('location_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qi_inspections',
                'ordering': ['-scheduled_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QIPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_period_start', models.DateField()),
                ('evaluation_period_end', models.DateField()),
                ('total_inspections', models.IntegerField(default=0)),
                ('on_time_inspections', models.IntegerField(default=0)),
                ('on_time_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_inspection_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('targets_met', models.IntegerField(default=0)),
                ('targets_missed', models.IntegerField(default=0)),
                ('quality_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qi_performance',
                'ordering': ['-evaluation_period_end'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SLARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('rule_description', models.TextField(blank=True, null=True)),
                ('deadline_days', models.IntegerField()),
                ('warning_threshold_days', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sla_rules',
                'ordering': ['rule_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_audit_logs',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('setting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('setting_type', models.CharField(choices=[('String', 'String'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('JSON', 'JSON')], max_length=50)),
                ('setting_description', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
                'ordering': ['setting_key'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_position', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_contacts',
                'ordering': ['-is_primary', 'contact_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendorDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dispute_subject', models.CharField(max_length=255)),
                ('dispute_description', models.TextField()),
                ('dispute_status', models.CharField(choices=[('Open', 'Open'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Open', max_length=50)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendor_disputes',
                'ordering': ['-submitted_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('Suggestion', 'Suggestion'), ('Complaint', 'Complaint'), ('Compliment', 'Compliment')], max_length=50)),
                ('feedback_subject', models.CharField(max_length=255)),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Actioned', 'Actioned')], default='Pending', max_length=50)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendor_feedback',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, unique=True)),
                ('stage_description', models.TextField(blank=True, null=True)),
                ('stage_order', models.IntegerField(blank=True, null=True)),
                ('default_duration_days', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_stages',
                'ordering': ['stage_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgeingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField()),
                ('age_bracket', models.CharField(choices=[('0-3', '0-3 Months'), ('4-6', '4-6 Months'), ('7-9', '7-9 Months'), ('10+', '10 Months and Above')], max_length=10)),
                ('age_in_days', models.IntegerField()),
                ('age_in_months', models.IntegerField()),
                ('crew', models.CharField(blank=True, max_length=50, null=True)),
                ('status_at_analysis', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ageing_analysis',
                'ordering': ['-analysis_date', '-age_in_days'],
            },
        ),
        migrations.CreateModel(
            name='BackjobMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('issue_category', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_date', models.DateField()),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('actual_resolution_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=50)),
                ('days_pending', models.IntegerField(default=0)),
                ('is_overdue', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backjob_monitoring',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='CrewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_code', models.CharField(max_length=50, unique=True)),
                ('crew_name', models.CharField(max_length=100)),
                ('weight_a', models.IntegerField(default=4)),
                ('weight_b', models.IntegerField(default=6)),
                ('weight_c', models.IntegerField(default=4)),
                ('weight_d', models.IntegerField(default=3)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1.8245, max_digits=10)),
                ('working_hours_per_day', models.IntegerField(default=8)),
                ('working_days_per_month', models.IntegerField(default=26)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crew_types',
                'ordering': ['crew_name'],
            },
        ),
        migrations.CreateModel(
            name='DailyCrewMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_date', models.DateField()),
                ('value_a', models.IntegerField(default=0)),
                ('value_b', models.IntegerField(default=0)),
                ('value_c', models.IntegerField(default=0)),
                ('value_d', models.IntegerField(default=0)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weighted_productivity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_peso_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weekly_peso_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('daily_peso_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_crew_monitoring',
                'ordering': ['-monitoring_date'],
            },
        ),
        migrations.CreateModel(
            name='PCAGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('target_completion_count', models.IntegerField(default=0)),
                ('target_conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pca_goals',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='PCASummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('ytd_energized', models.IntegerField(default=0)),
                ('carry_over_from_previous_year', models.IntegerField(default=0)),
                ('cancelled_count', models.IntegerField(default=0)),
                ('new_work_orders_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('completion_vs_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('performance_completion_index', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('crew_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PCA Summaries',
                'db_table': 'pca_summary',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='QIMonthlyAccomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('week1_count', models.IntegerField(default=0)),
                ('week2_count', models.IntegerField(default=0)),
                ('week3_count', models.IntegerField(default=0)),
                ('week4_count', models.IntegerField(default=0)),
                ('week5_count', models.IntegerField(default=0)),
                ('total_inspections', models.IntegerField(default=0)),
                ('target_inspections', models.IntegerField(default=0)),
                ('target_met', models.BooleanField(default=False)),
                ('achievement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qi_monthly_accomplishments',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='QIWeeklyAccomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('monday_count', models.IntegerField(default=0)),
                ('tuesday_count', models.IntegerField(default=0)),
                ('wednesday_count', models.IntegerField(default=0)),
                ('thursday_count', models.IntegerField(default=0)),
                ('friday_count', models.IntegerField(default=0)),
                ('saturday_count', models.IntegerField(default=0)),
                ('sunday_count', models.IntegerField(default=0)),
                ('total_inspections', models.IntegerField(default=0)),
                ('target_inspections', models.IntegerField(default=0)),
                ('target_met', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qi_weekly_accomplishments',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_roles',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='VendorProductivityMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('ytd_accomplishment', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monthly_accomplishment', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ytd_capability', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monthly_capability', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('declared_manpower', models.IntegerField(default=0)),
                ('actual_capability_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('productivity_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_productivity_monthly',
                'ordering': ['-month', 'vendor'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('COC', 'Certificate of Completion'), ('PERMIT', 'Permit'), ('INSPECTION', 'Inspection Report'), ('INVOICE', 'Invoice'), ('OTHER', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='work_orders/%Y/%m/')),
                ('document_path', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'work_order_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='cocsubmission',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='cocsubmission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='cocsubmission',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='kpiperformance',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='kpiperformance',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='kpiperformance',
            name='team',
        ),
        migrations.RemoveField(
            model_name='projectbilling',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='projectbilling',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectriskassessment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='qiaudit',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='qiaudit',
            name='project',
        ),
        migrations.RemoveField(
            model_name='qiinspector',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qiperformancelog',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='qiperformancelog',
            name='logged_by',
        ),
        migrations.DeleteModel(
            name='SLADefinition',
        ),
        migrations.DeleteModel(
            name='SPTConfiguration',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_lead',
        ),
        migrations.RemoveField(
            model_name='vendorbilling',
            name='vendor',
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'managed': False, 'ordering': ['doc_type_name']},
        ),
        migrations.AlterModelOptions(
            name='escalation',
            options={'managed': False, 'ordering': ['-escalation_date']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'managed': False, 'ordering': ['template_name']},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name_plural': 'Penalties'},
        ),
        migrations.AlterModelOptions(
            name='penaltyrule',
            options={'managed': False, 'ordering': ['rule_name']},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['module_name', 'permission_name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectdocument',
            options={'managed': False, 'ordering': ['-upload_date']},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role', 'permission']},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'managed': False, 'ordering': ['sector_name']},
        ),
        migrations.AlterModelOptions(
            name='slatracking',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'managed': False, 'ordering': ['vendor_name']},
        ),
        migrations.AlterModelOptions(
            name='vendorperformance',
            options={'managed': False, 'ordering': ['-evaluation_date']},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-date_received_jacket']},
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='description',
            new_name='permission_description',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='manhours',
            new_name='total_manhours',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='labor_cost',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='material_cost',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='project',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='wo_number',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='wo_type',
        ),
        migrations.AddField(
            model_name='permission',
            name='module_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_super_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='area_of_responsibility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assigned_qi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qi_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='billed_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='workorder',
            name='c1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='clerk_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='date_audited',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='date_coc_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='date_energized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='date_for_audit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='date_received_awarding',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='date_received_jacket',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='days_from_audit_to_billing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='days_from_coc_to_audit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='days_from_energized_to_coc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='de_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='delay_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='eam_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('VIP', 'VIP'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='target_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_resolution_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='meralcoapp.vendor'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vendor_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wo_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wo_initiator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wo_no',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='meralcoapp.permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_crew',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('FOR AUDIT', 'For Audit'), ('AUDITED', 'Audited'), ('NO COC', 'No COC'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=50),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['wo_no'], name='work_orders_wo_no_37434b_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='work_orders_status_3f6c76_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['vendor'], name='work_orders_vendor__232449_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assigned_crew'], name='work_orders_assigne_7b2ee1_idx'),
        ),
        migrations.AddField(
            model_name='ageinganalysis',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ageing_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ageinganalysis',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ageing_records', to='meralcoapp.workorder'),
        ),
        migrations.AddField(
            model_name='backjobmonitoring',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_backjobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backjobmonitoring',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backjobs', to='meralcoapp.workorder'),
        ),
        migrations.AddField(
            model_name='dailycrewmonitoring',
            name='crew_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='meralcoapp.crewtype'),
        ),
        migrations.AddField(
            model_name='qimonthlyaccomplishment',
            name='qi_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_accomplishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qiweeklyaccomplishment',
            name='qi_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_accomplishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='meralcoapp.userrole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='meralcoapp.userrole'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorproductivitymonthly',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_productivity', to='meralcoapp.vendor'),
        ),
        migrations.AddField(
            model_name='workorderdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wo_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderdocument',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wo_documents', to='meralcoapp.workorder'),
        ),
        migrations.DeleteModel(
            name='ChangeHistory',
        ),
        migrations.DeleteModel(
            name='COCSubmission',
        ),
        migrations.DeleteModel(
            name='KPIDefinition',
        ),
        migrations.DeleteModel(
            name='KPIPerformance',
        ),
        migrations.DeleteModel(
            name='ProjectBilling',
        ),
        migrations.DeleteModel(
            name='ProjectRiskAssessment',
        ),
        migrations.DeleteModel(
            name='QIAudit',
        ),
        migrations.DeleteModel(
            name='QIInspector',
        ),
        migrations.DeleteModel(
            name='QIPerformanceLog',
        ),
        migrations.DeleteModel(
            name='SystemConfig',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='VendorBilling',
        ),
        migrations.AddIndex(
            model_name='ageinganalysis',
            index=models.Index(fields=['analysis_date'], name='ageing_anal_analysi_fbcaff_idx'),
        ),
        migrations.AddIndex(
            model_name='ageinganalysis',
            index=models.Index(fields=['age_bracket'], name='ageing_anal_age_bra_6a1f13_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycrewmonitoring',
            index=models.Index(fields=['monitoring_date'], name='daily_crew__monitor_385789_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycrewmonitoring',
            index=models.Index(fields=['crew_type'], name='daily_crew__crew_ty_b274e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycrewmonitoring',
            unique_together={('crew_type', 'monitoring_date')},
        ),
        migrations.AlterUniqueTogether(
            name='qimonthlyaccomplishment',
            unique_together={('qi_user', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='qiweeklyaccomplishment',
            unique_together={('qi_user', 'week_start_date')},
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterUniqueTogether(
            name='vendorproductivitymonthly',
            unique_together={('vendor', 'month')},
        ),
    ]
