# Generated by Django 5.1.6 on 2025-10-20 15:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('meralcoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('change_type', models.CharField(choices=[('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'change_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DelayFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(max_length=100, unique=True)),
                ('factor_category', models.CharField(blank=True, max_length=50, null=True)),
                ('factor_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delay_factors',
                'ordering': ['factor_category', 'factor_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('overdue_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_compliance',
                'ordering': ['project', 'doc_type'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('rule_description', models.TextField(blank=True, null=True)),
                ('trigger_condition', models.CharField(max_length=255)),
                ('delay_threshold_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'escalation_rules',
                'ordering': ['rule_name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_name', models.CharField(max_length=100, unique=True)),
                ('inspection_description', models.TextField(blank=True, null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inspection_types',
                'ordering': ['inspection_name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Unpaid', max_length=50)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_days', models.IntegerField()),
                ('delay_start_date', models.DateField()),
                ('delay_end_date', models.DateField(blank=True, null=True)),
                ('responsible_party', models.CharField(blank=True, choices=[('Vendor', 'Vendor'), ('Internal', 'Internal'), ('External', 'External')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_delays',
                'ordering': ['-delay_start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=255)),
                ('milestone_description', models.TextField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('milestone_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_milestones',
                'ordering': ['milestone_order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, unique=True)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('status_order', models.IntegerField(blank=True, null=True)),
                ('status_color', models.CharField(blank=True, max_length=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project Statuses',
                'db_table': 'project_status',
                'ordering': ['status_order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_team',
                'ordering': ['project', '-is_active'],
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Blocked', 'Blocked')], default='Pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_current_stage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_workflow',
                'ordering': ['project', 'stage__stage_order'],
            },
        ),
        migrations.CreateModel(
            name='QIDailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('target_audits', models.IntegerField()),
                ('actual_audits', models.IntegerField(default=0)),
                ('target_met', models.BooleanField(default=False)),
                ('reason_not_met', models.TextField(blank=True, null=True)),
                ('reason_category', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qi_daily_targets',
                'ordering': ['-target_date'],
            },
        ),
        migrations.CreateModel(
            name='QIInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('inspection_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Conditional', 'Conditional')], max_length=50, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('photos_uploaded', models.BooleanField(default=False)),
                ('location_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qi_inspections',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='QIPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_period_start', models.DateField()),
                ('evaluation_period_end', models.DateField()),
                ('total_inspections', models.IntegerField(default=0)),
                ('on_time_inspections', models.IntegerField(default=0)),
                ('on_time_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_inspection_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('targets_met', models.IntegerField(default=0)),
                ('targets_missed', models.IntegerField(default=0)),
                ('quality_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qi_performance',
                'ordering': ['-evaluation_period_end'],
            },
        ),
        migrations.CreateModel(
            name='SLARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('rule_description', models.TextField(blank=True, null=True)),
                ('deadline_days', models.IntegerField()),
                ('warning_threshold_days', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sla_rules',
                'ordering': ['rule_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('setting_type', models.CharField(choices=[('String', 'String'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('JSON', 'JSON')], max_length=50)),
                ('setting_description', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
                'ordering': ['setting_key'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_roles',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_position', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_contacts',
                'ordering': ['-is_primary', 'contact_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dispute_subject', models.CharField(max_length=255)),
                ('dispute_description', models.TextField()),
                ('dispute_status', models.CharField(choices=[('Open', 'Open'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Open', max_length=50)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendor_disputes',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('Suggestion', 'Suggestion'), ('Complaint', 'Complaint'), ('Compliment', 'Compliment')], max_length=50)),
                ('feedback_subject', models.CharField(max_length=255)),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Actioned', 'Actioned')], default='Pending', max_length=50)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendor_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, unique=True)),
                ('stage_description', models.TextField(blank=True, null=True)),
                ('stage_order', models.IntegerField(blank=True, null=True)),
                ('default_duration_days', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_stages',
                'ordering': ['stage_order'],
            },
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='cocsubmission',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='cocsubmission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='cocsubmission',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='kpiperformance',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='kpiperformance',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='kpiperformance',
            name='team',
        ),
        migrations.RemoveField(
            model_name='projectbilling',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='projectbilling',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectriskassessment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='qiaudit',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='qiaudit',
            name='project',
        ),
        migrations.RemoveField(
            model_name='qiinspector',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qiperformancelog',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='qiperformancelog',
            name='logged_by',
        ),
        migrations.RemoveField(
            model_name='slatracking',
            name='sla',
        ),
        migrations.DeleteModel(
            name='SPTConfiguration',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_lead',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.RemoveField(
            model_name='vendorbilling',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['doc_type_name']},
        ),
        migrations.AlterModelOptions(
            name='escalation',
            options={'ordering': ['-escalation_date']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['template_name']},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Penalties'},
        ),
        migrations.AlterModelOptions(
            name='penaltyrule',
            options={'ordering': ['rule_name']},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['module_name', 'permission_name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectdocument',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role', 'permission']},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['sector_name']},
        ),
        migrations.AlterModelOptions(
            name='slatracking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['vendor_name']},
        ),
        migrations.AlterModelOptions(
            name='vendorperformance',
            options={'ordering': ['-evaluation_date']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_status_fce6f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_cedf2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='penalty',
            name='penalties_vendor__91a5b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='penalty',
            name='penalties_status_2c0e89_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_status_6303d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_assigne_f716a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_team_id_f935b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_wmtrl_d_10218c_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_fcomp_d_ca5833_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_project_2a78ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='slatracking',
            name='sla_trackin_status_4275b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='slatracking',
            name='sla_trackin_due_dat_7aadea_idx',
        ),
        migrations.RenameField(
            model_name='documenttype',
            old_name='description',
            new_name='doc_type_description',
        ),
        migrations.RenameField(
            model_name='escalation',
            old_name='response_details',
            new_name='resolution',
        ),
        migrations.RenameField(
            model_name='escalation',
            old_name='response_received_at',
            new_name='resolution_date',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='message_body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='body_template',
            new_name='template_body',
        ),
        migrations.RenameField(
            model_name='penalty',
            old_name='memo_sent_date',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='description',
            new_name='permission_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='actual_completion_date',
            new_name='actual_billing_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='appr_date',
            new_name='completion_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_value',
            new_name='contract_value',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='closed_date',
            new_name='expected_billing_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='is_aging',
            new_name='is_delayed',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='projectdocument',
            old_name='approved_at',
            new_name='approval_date',
        ),
        migrations.RenameField(
            model_name='projectdocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='projectdocument',
            old_name='file_size_kb',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='slatracking',
            old_name='days_overdue',
            new_name='breach_days',
        ),
        migrations.RenameField(
            model_name='slatracking',
            old_name='days_used',
            new_name='days_taken',
        ),
        migrations.RenameField(
            model_name='slatracking',
            old_name='breach_reason',
            new_name='waiver_reason',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='vendorperformance',
            old_name='measurement_period_end',
            new_name='evaluation_date',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='doc_type_code',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='sla_days',
        ),
        migrations.RemoveField(
            model_name='escalation',
            name='escalated_by',
        ),
        migrations.RemoveField(
            model_name='escalation',
            name='escalated_to',
        ),
        migrations.RemoveField(
            model_name='escalation',
            name='escalation_level',
        ),
        migrations.RemoveField(
            model_name='escalation',
            name='response_required_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='project',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='template',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='subject_template',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='template_code',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='trigger_event',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='memo_generated',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='penalty_percentage',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='status',
        ),
        migrations.RemoveField(
            model_name='penaltyrule',
            name='max_penalty_percentage',
        ),
        migrations.RemoveField(
            model_name='penaltyrule',
            name='penalty_per_day',
        ),
        migrations.RemoveField(
            model_name='penaltyrule',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='aging_category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='applied_load',
        ),
        migrations.RemoveField(
            model_name='project',
            name='assigned_vendor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='fcomp_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_revenue',
        ),
        migrations.RemoveField(
            model_name='project',
            name='manhours',
        ),
        migrations.RemoveField(
            model_name='project',
            name='priority_level',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_subtype',
        ),
        migrations.RemoveField(
            model_name='project',
            name='spt_days',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_completion_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='wmtrl_date',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='vendorperformance',
            name='average_delay_days',
        ),
        migrations.RemoveField(
            model_name='vendorperformance',
            name='completed_late',
        ),
        migrations.RemoveField(
            model_name='vendorperformance',
            name='completed_on_time',
        ),
        migrations.RemoveField(
            model_name='vendorperformance',
            name='measurement_period_start',
        ),
        migrations.RemoveField(
            model_name='vendorperformance',
            name='total_penalties',
        ),
        migrations.RemoveField(
            model_name='vendorperformance',
            name='total_projects',
        ),
        migrations.AddField(
            model_name='escalation',
            name='escalated_from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalation',
            name='escalated_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalation',
            name='escalation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalation',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='response_delay_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_entity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='meralcoapp.project'),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='template_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='dispute_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='dispute_resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='penalty_rule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='meralcoapp.penaltyrule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penalty',
            name='penalty_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Paid', 'Paid'), ('Waived', 'Waived'), ('Disputed', 'Disputed')], default='Draft', max_length=50),
        ),
        migrations.AddField(
            model_name='penalty',
            name='violation_date',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penalty',
            name='waiver_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penaltyrule',
            name='maximum_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='penaltyrule',
            name='minimum_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='penaltyrule',
            name='penalty_formula',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penaltyrule',
            name='rule_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penaltyrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='penaltyrule',
            name='violation_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='module_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_qi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qi_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='delay_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='project_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_score',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='meralcoapp.vendor'),
        ),
        migrations.AddField(
            model_name='project',
            name='wo_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='document_path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sectors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sector',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slatracking',
            name='is_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slatracking',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_waivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slatracking',
            name='waiver_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='blacklist_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='compliance_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorperformance',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorperformance',
            name='document_submission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendorperformance',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorperformance',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='doc_type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Push', 'Push'), ('In-App', 'In-App')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Read', 'Read')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Push', 'Push')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='delay_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_waivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penaltyrule',
            name='rule_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='meralcoapp.sector'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='meralcoapp.documenttype'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='meralcoapp.permission'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='slatracking',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Met', 'Met'), ('Breached', 'Breached'), ('Waived', 'Waived')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='compliance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='on_time_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='quality_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentcompliance',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='meralcoapp.documenttype'),
        ),
        migrations.AddField(
            model_name='documentcompliance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_compliance', to='meralcoapp.project'),
        ),
        migrations.AddField(
            model_name='escalationrule',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_rules', to='meralcoapp.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='escalation_rule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='meralcoapp.escalationrule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='meralcoapp.project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='meralcoapp.vendor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='meralcoapp.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_delays', to='meralcoapp.delayfactor'),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='meralcoapp.project'),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_delays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='meralcoapp.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='meralcoapp.projectstatus'),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='meralcoapp.project'),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectworkflow',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectworkflow',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='meralcoapp.project'),
        ),
        migrations.AddField(
            model_name='qidailytarget',
            name='qi_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qiinspection',
            name='assigned_qi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qiinspection',
            name='inspection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='meralcoapp.inspectiontype'),
        ),
        migrations.AddField(
            model_name='qiinspection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='meralcoapp.project'),
        ),
        migrations.AddField(
            model_name='qiperformance',
            name='qi_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slatracking',
            name='sla_rule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='meralcoapp.slarule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationrule',
            name='escalate_to_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rules', to='meralcoapp.userrole'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='meralcoapp.userrole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='meralcoapp.userrole'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='meralcoapp.vendor'),
        ),
        migrations.AddField(
            model_name='vendordispute',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendordispute',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='meralcoapp.project'),
        ),
        migrations.AddField(
            model_name='vendordispute',
            name='related_penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='meralcoapp.penalty'),
        ),
        migrations.AddField(
            model_name='vendordispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendordispute',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='meralcoapp.vendor'),
        ),
        migrations.AddField(
            model_name='vendorfeedback',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorfeedback',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='meralcoapp.vendor'),
        ),
        migrations.AddField(
            model_name='slarule',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_rules', to='meralcoapp.workflowstage'),
        ),
        migrations.AddField(
            model_name='projectworkflow',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workflows', to='meralcoapp.workflowstage'),
        ),
        migrations.DeleteModel(
            name='ChangeHistory',
        ),
        migrations.DeleteModel(
            name='COCSubmission',
        ),
        migrations.DeleteModel(
            name='KPIDefinition',
        ),
        migrations.DeleteModel(
            name='KPIPerformance',
        ),
        migrations.DeleteModel(
            name='ProjectBilling',
        ),
        migrations.DeleteModel(
            name='ProjectRiskAssessment',
        ),
        migrations.DeleteModel(
            name='QIAudit',
        ),
        migrations.DeleteModel(
            name='QIInspector',
        ),
        migrations.DeleteModel(
            name='QIPerformanceLog',
        ),
        migrations.DeleteModel(
            name='SLADefinition',
        ),
        migrations.DeleteModel(
            name='SystemConfig',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='VendorBilling',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
        migrations.AlterUniqueTogether(
            name='qidailytarget',
            unique_together={('qi_user', 'target_date')},
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
