# Generated by Django 5.2.7 on 2026-01-12 10:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meralcoapp', '0002_changelog_delayfactor_documentcompliance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='EmailNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('KPI_DAILY', 'Daily KPI Report'), ('BACKJOB', 'Backjob Alert'), ('OVERDUE_WO', 'Overdue Work Orders'), ('SLA_BREACH', 'SLA Breach Alert')], max_length=50)),
                ('notification_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('email_content', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_notification_log',
                'ordering': ['-notification_date'],
                'unique_together': {('notification_type', 'notification_date', 'recipient_email')},
            },
        ),
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_type', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('threshold_green', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('threshold_yellow', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('threshold_red', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kpi_targets',
                'ordering': ['-period_start'],
                'unique_together': {('kpi_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='VendorDailyActivity',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField(default=django.utils.timezone.now)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('team_leader', models.CharField(blank=True, max_length=100, null=True)),
                ('design_engineer', models.CharField(blank=True, max_length=100, null=True)),
                ('crew_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crew_composition', models.JSONField(blank=True, default=dict)),
                ('work_orders', models.JSONField(blank=True, default=list)),
                ('activity_description', models.TextField()),
                ('status', models.CharField(choices=[('SIGNED_ON', 'Signed On'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CAUTION', 'Caution Required')], default='SIGNED_ON', max_length=50)),
                ('has_caution', models.BooleanField(default=False)),
                ('caution_details', models.TextField(blank=True, null=True)),
                ('activity_photos', models.JSONField(blank=True, default=list)),
                ('signed_on_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_on_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_activities', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='meralcoapp.vendor')),
            ],
            options={
                'db_table': 'vendor_daily_activities',
                'ordering': ['-activity_date', '-signed_on_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorActivityPhoto',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_type', models.CharField(choices=[('SIGN_ON', 'Sign On Photo'), ('PROGRESS', 'Progress Photo'), ('COMPLETION', 'Completion Photo'), ('CAUTION', 'Caution/Safety Photo')], max_length=50)),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='vendor_activities/%Y/%m/%d/')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('location_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='meralcoapp.vendordailyactivity')),
            ],
            options={
                'db_table': 'vendor_activity_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kpi_type', models.CharField(choices=[('CCTI', 'Customer Connection Timeliness Index'), ('PCA_CONVERSION', 'PCA Conversion Rate'), ('AGEING_COMPLETION', 'Completion of Ageing PCAs'), ('PAI_ADHERENCE', 'Adherence to Approved PAI SAIDI'), ('TERM_APT', 'PCA Termination/Modification APT'), ('TERM_RESOLUTION', 'PCA Termination Resolution'), ('PRDI', 'Project Resolution Duration Index'), ('COST_SETTLEMENT', 'WO Cost Settlement to RAB'), ('QUALITY_INDEX', 'Quality Management Index'), ('CAPABILITY_UTIL', 'Contractor Capability Utilization')], max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('kpi_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('numerator', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('denominator', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('calculation_details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kpi_snapshots',
                'ordering': ['-period_end', 'kpi_type'],
                'indexes': [models.Index(fields=['kpi_type', 'period_end'], name='kpi_snapsho_kpi_typ_ad637f_idx'), models.Index(fields=['period_start', 'period_end'], name='kpi_snapsho_period__11ae34_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vendordailyactivity',
            index=models.Index(fields=['vendor', 'activity_date'], name='vendor_dail_vendor__5621c5_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordailyactivity',
            index=models.Index(fields=['status'], name='vendor_dail_status_57e4a5_idx'),
        ),
    ]
