# Generated by Django 5.2.7 on 2026-01-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meralcoapp', '0003_alter_user_email_emailnotificationlog_kpitarget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoractivityphoto',
            name='uploaded_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendordailyactivity',
            name='signed_on_by',
            field=models.IntegerField(default=0),
        ),
    ]
