# Generated by Django 5.2.7 on 2025-12-05 04:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meralcoapp', '0003_remove_user_id_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectiontype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='id',
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='inspection_type_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='setting_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
