# Generated by Django 5.2.7 on 2025-12-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meralcoapp', '0004_remove_inspectiontype_id_remove_systemsetting_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='delayfactor',
            options={'managed': False, 'ordering': ['factor_category', 'factor_name']},
        ),
        migrations.AlterModelOptions(
            name='documentcompliance',
            options={'managed': False, 'ordering': ['project', 'doc_type']},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'managed': False, 'ordering': ['doc_type_name']},
        ),
        migrations.AlterModelOptions(
            name='escalation',
            options={'managed': False, 'ordering': ['-escalation_date']},
        ),
        migrations.AlterModelOptions(
            name='escalationrule',
            options={'managed': False, 'ordering': ['rule_name']},
        ),
        migrations.AlterModelOptions(
            name='inspectiontype',
            options={'managed': False, 'ordering': ['inspection_name']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': False, 'ordering': ['-invoice_date']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'managed': False, 'ordering': ['template_name']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False, 'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name_plural': 'Penalties'},
        ),
        migrations.AlterModelOptions(
            name='penaltyrule',
            options={'managed': False, 'ordering': ['rule_name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectdelay',
            options={'managed': False, 'ordering': ['-delay_start_date']},
        ),
        migrations.AlterModelOptions(
            name='projectdocument',
            options={'managed': False, 'ordering': ['-upload_date']},
        ),
        migrations.AlterModelOptions(
            name='projectmilestone',
            options={'managed': False, 'ordering': ['milestone_order']},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'managed': False, 'ordering': ['status_order'], 'verbose_name_plural': 'Project Statuses'},
        ),
        migrations.AlterModelOptions(
            name='projectteam',
            options={'managed': False, 'ordering': ['project', '-is_active']},
        ),
        migrations.AlterModelOptions(
            name='projectworkflow',
            options={'managed': False, 'ordering': ['project', 'stage__stage_order']},
        ),
        migrations.AlterModelOptions(
            name='qidailytarget',
            options={'managed': False, 'ordering': ['-target_date']},
        ),
        migrations.AlterModelOptions(
            name='qiinspection',
            options={'managed': False, 'ordering': ['-scheduled_date']},
        ),
        migrations.AlterModelOptions(
            name='qiperformance',
            options={'managed': False, 'ordering': ['-evaluation_period_end']},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'managed': False, 'ordering': ['sector_name']},
        ),
        migrations.AlterModelOptions(
            name='slarule',
            options={'managed': False, 'ordering': ['rule_name']},
        ),
        migrations.AlterModelOptions(
            name='slatracking',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='systemauditlog',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'managed': False, 'ordering': ['setting_key']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'managed': False, 'ordering': ['vendor_name']},
        ),
        migrations.AlterModelOptions(
            name='vendorcontact',
            options={'managed': False, 'ordering': ['-is_primary', 'contact_name']},
        ),
        migrations.AlterModelOptions(
            name='vendordispute',
            options={'managed': False, 'ordering': ['-submitted_date']},
        ),
        migrations.AlterModelOptions(
            name='vendorfeedback',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendorperformance',
            options={'managed': False, 'ordering': ['-evaluation_date']},
        ),
        migrations.AlterModelOptions(
            name='workflowstage',
            options={'managed': False, 'ordering': ['stage_order']},
        ),
    ]
