# Generated by Django 5.2.7 on 2026-01-25 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meralcoapp', '0004_alter_vendoractivityphoto_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='workorderdocument',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='workorderdocument',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='workorderdocument',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='workorderdocument',
            name='approved_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorderdocument',
            name='file',
            field=models.FileField(default='', upload_to='work_order_documents/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorderdocument',
            name='uploaded_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='workorderdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workorderdocument',
            name='document_path',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorderdocument',
            name='document_type',
            field=models.CharField(choices=[('COC', 'Certificate of Completion'), ('PHOTO', 'Site Photo'), ('PERMIT', 'Building Permit'), ('RECEIPT', 'Material Receipt'), ('SAFETY', 'Safety Compliance Form'), ('DRAWING', 'As-Built Drawing'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workorderdocument',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorderdocument',
            name='work_order',
            field=models.ForeignKey(db_column='work_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='meralcoapp.workorder'),
        ),
    ]
