# Generated by Django 5.2.7 on 2026-04-23 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meralcoapp', '0005_alter_workorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workorder',
            table='workorders',
        ),
        migrations.CreateModel(
            name='ArchiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_date', models.DateTimeField(auto_now_add=True)),
                ('retention_period_years', models.IntegerField(default=10)),
                ('expiry_date', models.DateTimeField()),
                ('document_count', models.IntegerField(default=0)),
                ('document_details', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_actions', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_logs', to='meralcoapp.qiinspection')),
            ],
            options={
                'db_table': 'archive_logs',
                'ordering': ['-archive_date'],
            },
        ),
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('defect_id', models.AutoField(primary_key=True, serialize=False)),
                ('defect_type', models.CharField(max_length=100)),
                ('defect_category', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('related_checklist_items', models.JSONField(default=list, help_text='List of checklist item IDs that caused this defect')),
                ('photos', models.JSONField(blank=True, default=list)),
                ('location_gps', models.CharField(blank=True, max_length=100)),
                ('qi_notes', models.TextField(blank=True)),
                ('qi_signature', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction_status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending Vendor Action'), ('SUBMITTED', 'Correction Submitted'), ('APPROVED', 'Correction Approved'), ('REJECTED', 'Correction Rejected'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('correction_due_date', models.DateField(blank=True, null=True)),
                ('correction_photos', models.JSONField(blank=True, default=list)),
                ('correction_notes', models.TextField(blank=True)),
                ('correction_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('correction_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_corrections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_defects', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='meralcoapp.qiinspection')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='meralcoapp.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_defects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'defect_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectCorrectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Correction Submitted'), ('APPROVED', 'Correction Approved'), ('REJECTED', 'Correction Rejected'), ('RESUBMITTED', 'Correction Resubmitted')], max_length=20)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_history', to='meralcoapp.defectreport')),
            ],
            options={
                'verbose_name_plural': 'Defect correction histories',
                'db_table': 'defect_correction_history',
                'ordering': ['-action_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_category', models.CharField(blank=True, max_length=100)),
                ('item_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('NA', 'Not Applicable'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo URLs/paths')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_items', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='meralcoapp.qiinspection')),
            ],
            options={
                'db_table': 'inspection_checklist_items',
                'ordering': ['inspection', 'item_order', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('FAILED_ITEMS', 'Failed Checklist Items'), ('MISSING_PHOTOS', 'Missing Required Photos'), ('INCOMPLETE_DATA', 'Incomplete Inspection Data')], max_length=50)),
                ('item_count', models.IntegerField(default=0)),
                ('requires_action', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING_QI_REVIEW', 'Pending QI Review'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING_QI_REVIEW', max_length=20)),
                ('ai_suggestions', models.JSONField(blank=True, default=dict, help_text='AI-generated grouping and severity suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='meralcoapp.qiinspection')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspection_flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_image', models.ImageField(upload_to='payment_receipts/%Y/%m/')),
                ('receipt_number', models.CharField(max_length=100)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Check', 'Check'), ('Cash', 'Cash'), ('Online Payment', 'Online Payment')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='meralcoapp.invoice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipts', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_receipts',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QIInspectionCorrectionPhoto',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='qi_corrections/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_photo_files', to='meralcoapp.qiinspection')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_correction_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qi_inspection_correction_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QIInspectionPhoto',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='qi_inspections/%Y/%m/')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('location_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='meralcoapp.qiinspection')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_qi_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qi_inspection_photos',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='defectreport',
            index=models.Index(fields=['inspection', 'correction_status'], name='defect_repo_inspect_690206_idx'),
        ),
        migrations.AddIndex(
            model_name='defectreport',
            index=models.Index(fields=['project', 'severity'], name='defect_repo_project_9479fc_idx'),
        ),
        migrations.AddIndex(
            model_name='defectreport',
            index=models.Index(fields=['correction_status', 'created_at'], name='defect_repo_correct_20e5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionchecklistitem',
            index=models.Index(fields=['inspection', 'status'], name='inspection__inspect_719b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionflag',
            index=models.Index(fields=['inspection', 'status'], name='inspection__inspect_929405_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionflag',
            index=models.Index(fields=['status', 'created_at'], name='inspection__status_8abfc4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['invoice', 'status'], name='payment_rec_invoice_84f100_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['status', 'uploaded_at'], name='payment_rec_status_5a7e6e_idx'),
        ),
    ]
